### ISSUE TITLE
POST to /posts should contains PARAMS "author" not "owner"

### ISSUE THREAD

**Issue by gerardramosm89** [udacity/reactnd-project-readable-starter#1]
going over the API as I was working on the project, one of the PARAMS to POST /posts needs to be changed (or atleast it seems like it, please correct me if I am wrong)

POST /posts
USAGE:
Add a new post

PARAMS:
id - UUID should be fine, but any unique id will work
timestamp - timestamp in whatever format you like, you can use Date.now() if you like
title - String
body - String
owner - String <-- should be changed
author - String <-- is what it needs to be
category: Any of the categories listed in categories.js. Feel free to extend this list as you desire.

get API returns
```{
        "id": "8xf0y6ziyjabvozdd253nd",
        "timestamp": 1467166872634,
        "title": "Udacity is the best place to learn React",
        "body": "Everyone says so after all.",
        "author": "thingtwo",
        "category": "react",
        "voteScore": 6,
        "deleted": false
    }
```

POSTing with owner will result in no author being returned for future calls. It did for me.

**Comment by forbiddenvoid** [comment]
Fixed!
