### ISSUE TITLE
Edit a comment does not work

### ISSUE THREAD

**Issue by josenaves** [udacity/reactnd-project-readable-starter#17]
I got this error when I try to edit a comment:

Error editing comment SyntaxError: Unexpected end of JSON input

PUT http://localhost:5001/comments/6ni6ok3ym7mf1p33lnez
{timestamp: 1506996267403, body: "A silly comment!!!!"}

**Comment by AramayisO** [comment]
This bug recently got fixed in [pull request #19](https://github.com/udacity/reactnd-project-readable-starter/pull/19). If you update your server code to the latest version, you should be able to update comments.

**Comment by josenaves** [comment]
:+1:
