### ISSUE TITLE
params for upvoting/downvoting comment missing

### ISSUE THREAD

**Issue by gerardramosm89** [udacity/reactnd-project-readable-starter#2]
POST /comments/:id
USAGE:
Used for voting on a comment.

##### also the comment creation API asks for "owner", should be "author"

<img width="587" alt="screen shot 2017-08-10 at 6 48 40 pm" src="https://user-images.githubusercontent.com/22526582/29198868-8fe01bc0-7dfc-11e7-9429-2313d7a283a3.png">

##### sending in POST to the said API with no options or even with options similar to the post endpoint doesn't result in score being incremented/decremented.

comment from said post:
<img width="510" alt="screen shot 2017-08-10 at 6 49 58 pm" src="https://user-images.githubusercontent.com/22526582/29198891-c2473080-7dfc-11e7-895a-56be86c1c5a3.png">

as always apologies in advance for any oversights on my part

**Comment by muratozgul** [comment]
Try `option` not `options`. And make sure you are sending the `Authorization` header as well.

**Comment by gerardramosm89** [comment]
yup. that was it.
